<?php

if (! defined('ABSPATH')) exit;

/**
 * Registers the wpbean-pgs/product-gallery Gutenberg block.
 *
 * The block is intentionally settings-free: all zoom configuration is managed
 * through Gallery Rules and assigned per-product or per-category. In the block
 * editor the block shows a skeleton placeholder with a link to the Rules page.
 * On the frontend the block delegates rendering to
 * WPBean_PGS_WC_Gallery_Loader::render_custom_gallery() so the exact same
 * gallery markup is produced whether the gallery is injected via the classic hook
 * or placed directly into a block template.
 *
 * Primary use-case: block (FSE) themes and page-builder templates where
 * `woocommerce_before_single_product_summary` does not fire.
 */
class WPBean_PGS_Block
{

	public function __construct()
	{
		add_action('init',                    [$this, 'register']);
		add_action('enqueue_block_editor_assets', [$this, 'pass_admin_url']);
	}

	// ── Registration ────────────────────────────────────────────────────────────

	/**
	 * Register the block type, merging block.json metadata with the PHP
	 * server-side render callback (the `render` field in block.json is
	 * intentionally omitted for WP < 6.1 compatibility).
	 */
	public function register()
	{
		if (! function_exists('register_block_type')) {
			return;
		}

		register_block_type(
			WPBean_PGS_PATH . '/includes/blocks/product-gallery',
			[
				'render_callback' => [$this, 'render'],
			]
		);
	}

	/**
	 * Expose the admin URL to the block editor so the placeholder "Manage
	 * Gallery Rules" link works inside the Site Editor (where the admin
	 * pages script localization may not have run).
	 *
	 * The handle `wpbean-product-gallery-editor-script` is auto-generated by
	 * register_block_type() from the block name + the editorScript field.
	 */
	public function pass_admin_url()
	{
		wp_add_inline_script(
			'wpbean-product-gallery-editor-script',
			sprintf(
				'window.WPBean_PGS_Options=window.WPBean_PGS_Options||{};'
					. 'window.WPBean_PGS_Options.adminUrl=%s;',
				wp_json_encode(admin_url())
			),
			'before'
		);
	}

	// ── Server-side render ───────────────────────────────────────────────────────

	/**
	 * Render callback for the wpbean-pgs/product-gallery block.
	 *
	 * When a `productId` attribute is set the block renders that specific
	 * product's gallery, making the block usable on any page. Without a
	 * `productId` it falls back to the global $product (standard product
	 * template behaviour).
	 *
	 * @param array    $attributes Block attributes.
	 * @param string   $content    Inner content (empty for a void block).
	 * @param WP_Block $block      The current block instance.
	 * @return string
	 */
	public function render($attributes, $content, $block)
	{
		global $product;

		$product_id      = isset($attributes['productId']) ? absint($attributes['productId']) : 0;
		$restore_product = $product;

		if ($product_id) {
			$product = wc_get_product($product_id); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound
		}

		if (! is_a($product, 'WC_Product')) {
			$product = $restore_product; // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound
			return '';
		}

		// When placed outside a product page and a specific product is pinned,
		// assets may not have been enqueued yet — mirror what the shortcode does.
		if ($product_id) {
			$this->maybe_enqueue_assets();
			WPBean_PGS_WC_Gallery_Loader::suppress_hook_render($product->get_id());
		}

		ob_start();
		(new WPBean_PGS_WC_Gallery_Loader())->render_custom_gallery(true);
		$output = ob_get_clean();

		$product = $restore_product; // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound

		return $output ?: '';
	}

	/**
	 * Enqueues zoom scripts and styles when not already loaded.
	 * Used when productId is set and the block lives outside a product page.
	 */
	private function maybe_enqueue_assets(): void
	{
		if (wp_script_is('wpbean-pgs-wc-gallery-script', 'enqueued')) {
			return;
		}

		$asset_file = WPBean_PGS_PATH . '/includes/frontend/assets/build/wpbean-wc-gallery.asset.php';

		if (! file_exists($asset_file)) {
			return;
		}

		$asset = include $asset_file;

		wp_enqueue_script(
			'wpbean-pgs-wc-gallery-script',
			plugins_url('includes/frontend/assets/build/wpbean-wc-gallery.js', WPBean_PGS_FILE),
			$asset['dependencies'],
			$asset['version'],
			['in_footer' => true]
		);

		wp_enqueue_style(
			'wpbean-pgs-wc-gallery-style',
			plugins_url('includes/frontend/assets/build/style-wpbean-wc-gallery.css', WPBean_PGS_FILE),
			[],
			$asset['version']
		);
	}
}
